/**
 * Curated density reference table (grams per milliliter).
 *
 * Used by:
 *   - the Agent Bridge (deterministic density suggestions + auto-created
 *     ingredient density defaults),
 *   - the density heuristics seed script (scripts/seed-densities.ts) so the
 *     global density_heuristics table starts populated,
 *   - the UI density picker (via /api/density-heuristics).
 *
 * Values are standard food-science references (USDA FoodData Central,
 * engineering handbooks) for common coffee-shop and small-restaurant
 * ingredients. They are defaults — owners should verify against their own
 * packs when accuracy matters. Densities assume packed/settled states where
 * noted; always prefer the specific product's label when available.
 */

export interface CuratedDensity {
  ingredientName: string;
  gramsPerMilliliter: number;
  category?: string;
  notes?: string;
}

export const CURATED_DENSITIES: CuratedDensity[] = [
  // ── Liquids (dairy & alt-milks) ─────────────────────────────────────────
  { ingredientName: "Water", gramsPerMilliliter: 1.0, category: "Liquids", notes: "Reference point (1 g/mL)" },
  { ingredientName: "Whole Milk", gramsPerMilliliter: 1.03, category: "Dairy", notes: "USDA whole milk 3.25%" },
  { ingredientName: "2% Milk", gramsPerMilliliter: 1.03, category: "Dairy" },
  { ingredientName: "Skim Milk", gramsPerMilliliter: 1.033, category: "Dairy" },
  { ingredientName: "Nonfat Milk", gramsPerMilliliter: 1.033, category: "Dairy" },
  { ingredientName: "Heavy Cream", gramsPerMilliliter: 0.994, category: "Dairy", notes: "36-40% fat" },
  { ingredientName: "Whipping Cream", gramsPerMilliliter: 0.99, category: "Dairy" },
  { ingredientName: "Half and Half", gramsPerMilliliter: 1.01, category: "Dairy" },
  { ingredientName: "Buttermilk", gramsPerMilliliter: 1.03, category: "Dairy" },
  { ingredientName: "Condensed Milk", gramsPerMilliliter: 1.3, category: "Dairy" },
  { ingredientName: "Evaporated Milk", gramsPerMilliliter: 1.07, category: "Dairy" },
  { ingredientName: "Almond Milk", gramsPerMilliliter: 1.0, category: "Dairy Alternatives", notes: "~0.99-1.01 depending on brand" },
  { ingredientName: "Oat Milk", gramsPerMilliliter: 1.02, category: "Dairy Alternatives" },
  { ingredientName: "Soy Milk", gramsPerMilliliter: 1.02, category: "Dairy Alternatives" },
  { ingredientName: "Coconut Milk", gramsPerMilliliter: 1.03, category: "Dairy Alternatives", notes: "Canned coconut milk ~1.03" },
  { ingredientName: "Coconut Cream", gramsPerMilliliter: 1.0, category: "Dairy Alternatives" },
  { ingredientName: "Rice Milk", gramsPerMilliliter: 1.02, category: "Dairy Alternatives" },
  { ingredientName: "Cashew Milk", gramsPerMilliliter: 1.0, category: "Dairy Alternatives" },
  { ingredientName: "Lactose Free Milk", gramsPerMilliliter: 1.03, category: "Dairy" },
  { ingredientName: "Greek Yogurt", gramsPerMilliliter: 1.04, category: "Dairy", notes: "≈1.04 g/mL" },
  { ingredientName: "Plain Yogurt", gramsPerMilliliter: 1.04, category: "Dairy" },
  { ingredientName: "Sour Cream", gramsPerMilliliter: 0.99, category: "Dairy" },
  { ingredientName: "Cream Cheese", gramsPerMilliliter: 1.01, category: "Dairy" },
  { ingredientName: "Butter", gramsPerMilliliter: 0.911, category: "Dairy", notes: "USDA butter" },
  { ingredientName: "Margarine", gramsPerMilliliter: 0.92, category: "Dairy Alternatives" },
  { ingredientName: "Ice Cream", gramsPerMilliliter: 0.86, category: "Dairy", notes: "Vanilla ice cream ~0.55-0.65 kg/L" },
  { ingredientName: "Gelato", gramsPerMilliliter: 0.9, category: "Dairy" },

  // ── Syrups & sweeteners ─────────────────────────────────────────────────
  { ingredientName: "Simple Syrup", gramsPerMilliliter: 1.22, category: "Syrups", notes: "1:1 sugar:water" },
  { ingredientName: "Rich Simple Syrup", gramsPerMilliliter: 1.32, category: "Syrups", notes: "2:1 sugar:water" },
  { ingredientName: "Vanilla Syrup", gramsPerMilliliter: 1.3, category: "Syrups" },
  { ingredientName: "Caramel Syrup", gramsPerMilliliter: 1.3, category: "Syrups" },
  { ingredientName: "Caramel Sauce", gramsPerMilliliter: 1.35, category: "Syrups" },
  { ingredientName: "Chocolate Syrup", gramsPerMilliliter: 1.3, category: "Syrups", notes: "Hershey's-style syrup" },
  { ingredientName: "Chocolate Sauce", gramsPerMilliliter: 1.3, category: "Syrups" },
  { ingredientName: "Mocha Sauce", gramsPerMilliliter: 1.3, category: "Syrups" },
  { ingredientName: "Hazelnut Syrup", gramsPerMilliliter: 1.25, category: "Syrups" },
  { ingredientName: "Pumpkin Spice Syrup", gramsPerMilliliter: 1.28, category: "Syrups" },
  { ingredientName: "Salted Caramel Syrup", gramsPerMilliliter: 1.3, category: "Syrups" },
  { ingredientName: "Agave Nectar", gramsPerMilliliter: 1.42, category: "Sweeteners" },
  { ingredientName: "Honey", gramsPerMilliliter: 1.42, category: "Sweeteners", notes: "USDA honey" },
  { ingredientName: "Maple Syrup", gramsPerMilliliter: 1.33, category: "Sweeteners" },
  { ingredientName: "Molasses", gramsPerMilliliter: 1.4, category: "Sweeteners" },
  { ingredientName: "Corn Syrup", gramsPerMilliliter: 1.38, category: "Sweeteners" },
  { ingredientName: "Sweetened Condensed Milk", gramsPerMilliliter: 1.3, category: "Sweeteners" },

  // ── Dry goods / baking ──────────────────────────────────────────────────
  { ingredientName: "All Purpose Flour", gramsPerMilliliter: 0.53, category: "Baking", notes: "Spooned, ~0.53 g/mL" },
  { ingredientName: "All-Purpose Flour", gramsPerMilliliter: 0.53, category: "Baking" },
  { ingredientName: "Bread Flour", gramsPerMilliliter: 0.55, category: "Baking" },
  { ingredientName: "Cake Flour", gramsPerMilliliter: 0.48, category: "Baking" },
  { ingredientName: "Pastry Flour", gramsPerMilliliter: 0.5, category: "Baking" },
  { ingredientName: "Whole Wheat Flour", gramsPerMilliliter: 0.55, category: "Baking" },
  { ingredientName: "Gluten Free Flour", gramsPerMilliliter: 0.5, category: "Baking" },
  { ingredientName: "Cornstarch", gramsPerMilliliter: 0.53, category: "Baking" },
  { ingredientName: "Cornmeal", gramsPerMilliliter: 0.62, category: "Baking" },
  { ingredientName: "Oats", gramsPerMilliliter: 0.4, category: "Baking", notes: "Rolled oats ~0.4 g/mL" },
  { ingredientName: "Rolled Oats", gramsPerMilliliter: 0.4, category: "Baking" },
  { ingredientName: "Quick Oats", gramsPerMilliliter: 0.38, category: "Baking" },
  { ingredientName: "Granulated Sugar", gramsPerMilliliter: 0.85, category: "Sweeteners", notes: "Settled granulated sugar" },
  { ingredientName: "White Sugar", gramsPerMilliliter: 0.85, category: "Sweeteners" },
  { ingredientName: "Brown Sugar", gramsPerMilliliter: 0.79, category: "Sweeteners", notes: "Packed brown sugar ~0.79-0.85" },
  { ingredientName: "Powdered Sugar", gramsPerMilliliter: 0.5, category: "Sweeteners", notes: "Confectioners' sugar" },
  { ingredientName: "Confectioners Sugar", gramsPerMilliliter: 0.5, category: "Sweeteners" },
  { ingredientName: "Cocoa Powder", gramsPerMilliliter: 0.5, category: "Baking", notes: "Unsweetened cocoa powder" },
  { ingredientName: "Dutch Process Cocoa", gramsPerMilliliter: 0.5, category: "Baking" },
  { ingredientName: "Baking Soda", gramsPerMilliliter: 0.9, category: "Baking" },
  { ingredientName: "Baking Powder", gramsPerMilliliter: 0.7, category: "Baking" },
  { ingredientName: "Salt", gramsPerMilliliter: 1.2, category: "Baking", notes: "Table salt ~1.2 g/mL" },
  { ingredientName: "Table Salt", gramsPerMilliliter: 1.2, category: "Baking" },
  { ingredientName: "Kosher Salt", gramsPerMilliliter: 0.72, category: "Baking", notes: "Diamond Crystal-style flakes" },
  { ingredientName: "Sea Salt", gramsPerMilliliter: 1.1, category: "Baking" },
  { ingredientName: "Yeast", gramsPerMilliliter: 0.6, category: "Baking", notes: "Dry yeast granules" },
  { ingredientName: "Active Dry Yeast", gramsPerMilliliter: 0.6, category: "Baking" },
  { ingredientName: "Instant Yeast", gramsPerMilliliter: 0.6, category: "Baking" },
  { ingredientName: "Cinnamon", gramsPerMilliliter: 0.5, category: "Spices", notes: "Ground cinnamon" },
  { ingredientName: "Ground Cinnamon", gramsPerMilliliter: 0.5, category: "Spices" },
  { ingredientName: "Nutmeg", gramsPerMilliliter: 0.5, category: "Spices", notes: "Ground nutmeg" },
  { ingredientName: "Ground Nutmeg", gramsPerMilliliter: 0.5, category: "Spices" },
  { ingredientName: "Ginger", gramsPerMilliliter: 0.5, category: "Spices", notes: "Ground ginger" },
  { ingredientName: "Ground Ginger", gramsPerMilliliter: 0.5, category: "Spices" },
  { ingredientName: "Vanilla Extract", gramsPerMilliliter: 0.88, category: "Flavorings" },
  { ingredientName: "Vanilla Bean Paste", gramsPerMilliliter: 1.1, category: "Flavorings" },
  { ingredientName: "Espresso", gramsPerMilliliter: 1.0, category: "Beverages", notes: "≈ water density" },
  { ingredientName: "Coffee", gramsPerMilliliter: 1.0, category: "Beverages", notes: "Brewed coffee ≈ water" },
  { ingredientName: "Brewed Coffee", gramsPerMilliliter: 1.0, category: "Beverages" },
  { ingredientName: "Cold Brew Concentrate", gramsPerMilliliter: 1.02, category: "Beverages" },
  { ingredientName: "Matcha Powder", gramsPerMilliliter: 0.45, category: "Beverages", notes: "Ceremonial matcha ~0.4-0.5" },
  { ingredientName: "Chai Concentrate", gramsPerMilliliter: 1.04, category: "Beverages" },

  // ── Oils & fats ─────────────────────────────────────────────────────────
  { ingredientName: "Vegetable Oil", gramsPerMilliliter: 0.92, category: "Oils" },
  { ingredientName: "Canola Oil", gramsPerMilliliter: 0.92, category: "Oils" },
  { ingredientName: "Olive Oil", gramsPerMilliliter: 0.91, category: "Oils" },
  { ingredientName: "Extra Virgin Olive Oil", gramsPerMilliliter: 0.91, category: "Oils" },
  { ingredientName: "Avocado Oil", gramsPerMilliliter: 0.92, category: "Oils" },
  { ingredientName: "Coconut Oil", gramsPerMilliliter: 0.92, category: "Oils", notes: "Liquid coconut oil" },
  { ingredientName: "Sesame Oil", gramsPerMilliliter: 0.92, category: "Oils" },
  { ingredientName: "Sunflower Oil", gramsPerMilliliter: 0.92, category: "Oils" },
  { ingredientName: "MCT Oil", gramsPerMilliliter: 0.94, category: "Oils" },
  { ingredientName: "Shortening", gramsPerMilliliter: 0.88, category: "Oils" },
  { ingredientName: "Lard", gramsPerMilliliter: 0.92, category: "Oils" },
  { ingredientName: "Ghee", gramsPerMilliliter: 0.9, category: "Oils" },

  // ── Fruits, vegetables & produce (whole-item approximations) ────────────
  { ingredientName: "Banana", gramsPerMilliliter: 0.94, category: "Produce", notes: "Flesh ~0.94 g/mL" },
  { ingredientName: "Apple", gramsPerMilliliter: 0.83, category: "Produce", notes: "Whole apple" },
  { ingredientName: "Strawberries", gramsPerMilliliter: 0.93, category: "Produce", notes: "Whole berries" },
  { ingredientName: "Strawberry Puree", gramsPerMilliliter: 1.03, category: "Produce" },
  { ingredientName: "Blueberries", gramsPerMilliliter: 0.85, category: "Produce" },
  { ingredientName: "Raspberries", gramsPerMilliliter: 0.86, category: "Produce" },
  { ingredientName: "Blackberries", gramsPerMilliliter: 0.87, category: "Produce" },
  { ingredientName: "Mango", gramsPerMilliliter: 1.05, category: "Produce" },
  { ingredientName: "Mango Puree", gramsPerMilliliter: 1.06, category: "Produce" },
  { ingredientName: "Pineapple", gramsPerMilliliter: 1.03, category: "Produce" },
  { ingredientName: "Pineapple Juice", gramsPerMilliliter: 1.05, category: "Beverages" },
  { ingredientName: "Orange", gramsPerMilliliter: 0.96, category: "Produce" },
  { ingredientName: "Orange Juice", gramsPerMilliliter: 1.05, category: "Beverages" },
  { ingredientName: "Lemon", gramsPerMilliliter: 0.97, category: "Produce" },
  { ingredientName: "Lemon Juice", gramsPerMilliliter: 1.03, category: "Beverages" },
  { ingredientName: "Lime", gramsPerMilliliter: 0.98, category: "Produce" },
  { ingredientName: "Lime Juice", gramsPerMilliliter: 1.03, category: "Beverages" },
  { ingredientName: "Grapefruit Juice", gramsPerMilliliter: 1.04, category: "Beverages" },
  { ingredientName: "Cranberry Juice", gramsPerMilliliter: 1.03, category: "Beverages" },
  { ingredientName: "Apple Juice", gramsPerMilliliter: 1.05, category: "Beverages" },
  { ingredientName: "Grape Juice", gramsPerMilliliter: 1.06, category: "Beverages" },
  { ingredientName: "Tomato", gramsPerMilliliter: 0.94, category: "Produce" },
  { ingredientName: "Tomato Puree", gramsPerMilliliter: 1.03, category: "Produce" },
  { ingredientName: "Tomato Sauce", gramsPerMilliliter: 1.05, category: "Produce" },
  { ingredientName: "Avocado", gramsPerMilliliter: 0.94, category: "Produce", notes: "Flesh" },
  { ingredientName: "Guacamole", gramsPerMilliliter: 0.98, category: "Produce" },
  { ingredientName: "Potato", gramsPerMilliliter: 1.08, category: "Produce" },
  { ingredientName: "Onion", gramsPerMilliliter: 0.94, category: "Produce" },
  { ingredientName: "Garlic", gramsPerMilliliter: 1.0, category: "Produce" },
  { ingredientName: "Carrot", gramsPerMilliliter: 1.02, category: "Produce" },
  { ingredientName: "Celery", gramsPerMilliliter: 0.92, category: "Produce" },
  { ingredientName: "Cucumber", gramsPerMilliliter: 0.95, category: "Produce" },
  { ingredientName: "Bell Pepper", gramsPerMilliliter: 0.94, category: "Produce" },
  { ingredientName: "Spinach", gramsPerMilliliter: 0.42, category: "Produce", notes: "Raw leaves, loosely packed" },
  { ingredientName: "Kale", gramsPerMilliliter: 0.3, category: "Produce", notes: "Raw chopped leaves" },
  { ingredientName: "Lettuce", gramsPerMilliliter: 0.36, category: "Produce" },
  { ingredientName: "Broccoli", gramsPerMilliliter: 0.61, category: "Produce", notes: "Chopped florets" },
  { ingredientName: "Mushrooms", gramsPerMilliliter: 0.6, category: "Produce", notes: "Sliced ~0.6 g/mL" },
  { ingredientName: "Coconut Shredded", gramsPerMilliliter: 0.35, category: "Baking", notes: "Shredded dried coconut" },
  { ingredientName: "Shredded Coconut", gramsPerMilliliter: 0.35, category: "Baking" },
  { ingredientName: "Raisins", gramsPerMilliliter: 0.6, category: "Baking" },
  { ingredientName: "Chocolate Chips", gramsPerMilliliter: 0.6, category: "Baking", notes: "Semi-sweet chips ~0.6 g/mL" },
  { ingredientName: "Semi Sweet Chocolate Chips", gramsPerMilliliter: 0.6, category: "Baking" },
  { ingredientName: "Dark Chocolate", gramsPerMilliliter: 1.2, category: "Baking", notes: "Solid chocolate bar ~1.2-1.3" },
  { ingredientName: "White Chocolate", gramsPerMilliliter: 1.2, category: "Baking" },
  { ingredientName: "Peanut Butter", gramsPerMilliliter: 1.08, category: "Spreads", notes: "Creamy peanut butter" },
  { ingredientName: "Almond Butter", gramsPerMilliliter: 1.06, category: "Spreads" },
  { ingredientName: "Nutella", gramsPerMilliliter: 1.2, category: "Spreads" },
  { ingredientName: "Jam", gramsPerMilliliter: 1.33, category: "Spreads" },
  { ingredientName: "Strawberry Jam", gramsPerMilliliter: 1.33, category: "Spreads" },
  { ingredientName: "Marmalade", gramsPerMilliliter: 1.3, category: "Spreads" },
  { ingredientName: "Hummus", gramsPerMilliliter: 1.03, category: "Spreads" },

  // ── Proteins & other kitchen staples ────────────────────────────────────
  { ingredientName: "Egg", gramsPerMilliliter: 1.03, category: "Proteins", notes: "Whole egg ~1.03 g/mL" },
  { ingredientName: "Egg Whites", gramsPerMilliliter: 1.04, category: "Proteins" },
  { ingredientName: "Egg Yolks", gramsPerMilliliter: 1.03, category: "Proteins" },
  { ingredientName: "Chicken Breast", gramsPerMilliliter: 1.05, category: "Proteins", notes: "Raw ~1.05 g/mL" },
  { ingredientName: "Ground Beef", gramsPerMilliliter: 1.0, category: "Proteins", notes: "Raw 80/20" },
  { ingredientName: "Bacon", gramsPerMilliliter: 0.94, category: "Proteins", notes: "Raw strips" },
  { ingredientName: "Tofu", gramsPerMilliliter: 1.05, category: "Proteins" },
  { ingredientName: "Tempeh", gramsPerMilliliter: 1.03, category: "Proteins" },
  { ingredientName: "Cheese", gramsPerMilliliter: 1.0, category: "Dairy", notes: "Hard cheese ~1.0-1.1" },
  { ingredientName: "Cheddar Cheese", gramsPerMilliliter: 1.05, category: "Dairy" },
  { ingredientName: "Mozzarella", gramsPerMilliliter: 1.03, category: "Dairy", notes: "Shredded ~0.6, block ~1.03" },
  { ingredientName: "Shredded Mozzarella", gramsPerMilliliter: 0.6, category: "Dairy" },
  { ingredientName: "Parmesan", gramsPerMilliliter: 1.08, category: "Dairy" },
  { ingredientName: "Feta", gramsPerMilliliter: 1.05, category: "Dairy" },
  { ingredientName: "Soy Sauce", gramsPerMilliliter: 1.12, category: "Condiments" },
  { ingredientName: "Hot Sauce", gramsPerMilliliter: 1.05, category: "Condiments" },
  { ingredientName: "Sriracha", gramsPerMilliliter: 1.1, category: "Condiments" },
  { ingredientName: "Ketchup", gramsPerMilliliter: 1.11, category: "Condiments" },
  { ingredientName: "Mustard", gramsPerMilliliter: 1.1, category: "Condiments" },
  { ingredientName: "Mayonnaise", gramsPerMilliliter: 0.91, category: "Condiments" },
  { ingredientName: "Vinegar", gramsPerMilliliter: 1.01, category: "Condiments" },
  { ingredientName: "White Vinegar", gramsPerMilliliter: 1.01, category: "Condiments" },
  { ingredientName: "Balsamic Vinegar", gramsPerMilliliter: 1.06, category: "Condiments" },
  { ingredientName: "Worcestershire Sauce", gramsPerMilliliter: 1.1, category: "Condiments" },
  { ingredientName: "Pesto", gramsPerMilliliter: 1.08, category: "Condiments" },
  { ingredientName: "Broth", gramsPerMilliliter: 1.0, category: "Stocks", notes: "Chicken/vegetable broth ≈ water" },
  { ingredientName: "Chicken Broth", gramsPerMilliliter: 1.0, category: "Stocks" },
  { ingredientName: "Vegetable Broth", gramsPerMilliliter: 1.0, category: "Stocks" },
  { ingredientName: "Beef Broth", gramsPerMilliliter: 1.0, category: "Stocks" },
  { ingredientName: "Coconut Water", gramsPerMilliliter: 1.02, category: "Beverages" },
  { ingredientName: "Soda", gramsPerMilliliter: 1.04, category: "Beverages", notes: "Carbonated soft drink" },
  { ingredientName: "Cola", gramsPerMilliliter: 1.04, category: "Beverages" },
  { ingredientName: "Sparkling Water", gramsPerMilliliter: 1.0, category: "Beverages" },
  { ingredientName: "Tonic Water", gramsPerMilliliter: 1.03, category: "Beverages" },
  { ingredientName: "Beer", gramsPerMilliliter: 1.01, category: "Beverages" },
  { ingredientName: "Wine", gramsPerMilliliter: 0.99, category: "Beverages" },
  { ingredientName: "Red Wine", gramsPerMilliliter: 0.99, category: "Beverages" },
  { ingredientName: "White Wine", gramsPerMilliliter: 0.99, category: "Beverages" },
  { ingredientName: "Whiskey", gramsPerMilliliter: 0.94, category: "Beverages" },
  { ingredientName: "Vodka", gramsPerMilliliter: 0.94, category: "Beverages" },
  { ingredientName: "Espresso Beans", gramsPerMilliliter: 0.42, category: "Coffee", notes: "Whole roasted beans ~0.4-0.45" },
  { ingredientName: "Coffee Beans", gramsPerMilliliter: 0.42, category: "Coffee" },
  { ingredientName: "Ground Coffee", gramsPerMilliliter: 0.38, category: "Coffee", notes: "Ground roasted ~0.33-0.4" },
  { ingredientName: "Instant Coffee", gramsPerMilliliter: 0.3, category: "Coffee", notes: "Instant granules" },
  { ingredientName: "Cocoa Nibs", gramsPerMilliliter: 0.5, category: "Baking" },
  { ingredientName: "Protein Powder", gramsPerMilliliter: 0.5, category: "Supplements", notes: "Whey protein ~0.5 g/mL" },
  { ingredientName: "Whey Protein", gramsPerMilliliter: 0.5, category: "Supplements" },
  { ingredientName: "Collagen Peptides", gramsPerMilliliter: 0.5, category: "Supplements" },
  { ingredientName: "Ice", gramsPerMilliliter: 0.92, category: "Beverages", notes: "Crushed ice ~0.55-0.9 depending on density" },
  { ingredientName: "Crushed Ice", gramsPerMilliliter: 0.6, category: "Beverages" },
  { ingredientName: "Milk Powder", gramsPerMilliliter: 0.45, category: "Dairy", notes: "Nonfat dry milk powder" },
  { ingredientName: "Nonfat Dry Milk", gramsPerMilliliter: 0.45, category: "Dairy" },
  { ingredientName: "Wheat Gluten", gramsPerMilliliter: 0.6, category: "Baking" },
  { ingredientName: "Rice", gramsPerMilliliter: 0.78, category: "Grains", notes: "Dry white rice" },
  { ingredientName: "White Rice", gramsPerMilliliter: 0.78, category: "Grains" },
  { ingredientName: "Brown Rice", gramsPerMilliliter: 0.75, category: "Grains" },
  { ingredientName: "Quinoa", gramsPerMilliliter: 0.7, category: "Grains", notes: "Dry quinoa" },
  { ingredientName: "Pasta", gramsPerMilliliter: 0.6, category: "Grains", notes: "Dry penne ~0.6 g/mL" },
  { ingredientName: "Dry Pasta", gramsPerMilliliter: 0.6, category: "Grains" },
  { ingredientName: "Beans", gramsPerMilliliter: 0.8, category: "Grains", notes: "Dry beans" },
  { ingredientName: "Black Beans", gramsPerMilliliter: 0.8, category: "Grains", notes: "Dry" },
  { ingredientName: "Chickpeas", gramsPerMilliliter: 0.8, category: "Grains", notes: "Dry" },
  { ingredientName: "Lentils", gramsPerMilliliter: 0.8, category: "Grains", notes: "Dry" },
  { ingredientName: "Almonds", gramsPerMilliliter: 0.6, category: "Nuts", notes: "Whole almonds" },
  { ingredientName: "Whole Almonds", gramsPerMilliliter: 0.6, category: "Nuts" },
  { ingredientName: "Sliced Almonds", gramsPerMilliliter: 0.35, category: "Nuts" },
  { ingredientName: "Walnuts", gramsPerMilliliter: 0.5, category: "Nuts", notes: "Chopped" },
  { ingredientName: "Pecans", gramsPerMilliliter: 0.5, category: "Nuts", notes: "Chopped" },
  { ingredientName: "Pistachios", gramsPerMilliliter: 0.55, category: "Nuts", notes: "Shelled" },
  { ingredientName: "Hazelnuts", gramsPerMilliliter: 0.55, category: "Nuts" },
  { ingredientName: "Peanuts", gramsPerMilliliter: 0.65, category: "Nuts" },
  { ingredientName: "Macadamia Nuts", gramsPerMilliliter: 0.55, category: "Nuts" },
  { ingredientName: "Cashews", gramsPerMilliliter: 0.55, category: "Nuts" },
  { ingredientName: "Sunflower Seeds", gramsPerMilliliter: 0.55, category: "Nuts", notes: "Shelled kernels" },
  { ingredientName: "Chia Seeds", gramsPerMilliliter: 0.7, category: "Nuts", notes: "Dry seeds" },
  { ingredientName: "Flax Seeds", gramsPerMilliliter: 0.65, category: "Nuts", notes: "Ground" },
  { ingredientName: "Granola", gramsPerMilliliter: 0.45, category: "Baking" },
  { ingredientName: "Breadcrumbs", gramsPerMilliliter: 0.42, category: "Baking" },
  { ingredientName: "Panko", gramsPerMilliliter: 0.2, category: "Baking", notes: "Panko breadcrumbs ~0.2 g/mL" },
  { ingredientName: "Croutons", gramsPerMilliliter: 0.15, category: "Baking" },
];
